/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hellskitchen;

import java.awt.Color;
import java.util.TimerTask;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import main.main;


/**
 *
 * @author Students
 */
public class LevelMap extends javax.swing.JFrame {

    /**
     * Creates new form frame3
     */
    public LevelMap() {
        initComponents();
        
        
        //levels
        lvl1.setOpaque(false);
        lvl1.setContentAreaFilled(false);
        lvl1.setBorderPainted(false);
        lvl1Animation.setVisible(false);
        lvl1Notif.setVisible(false);
        
        lvl2.setOpaque(false);
        lvl2.setContentAreaFilled(false);
        lvl2.setBorderPainted(false);
        lvl2Animation.setVisible(false);
        lvl2Notif.setVisible(false);
        
        lvl3.setOpaque(false);
        lvl3.setContentAreaFilled(false);
        lvl3.setBorderPainted(false);
        lvl3Animation.setVisible(false);
        lvl3Notif.setVisible(false);
        
       
        
        //buttons
        ExitBtn.setOpaque(false);
        ExitBtn.setContentAreaFilled(false);
        ExitBtn.setBorderPainted(false);
        Exit.setVisible(false);
        
        
        
         setLocationRelativeTo(null);
         jPanel1.setBackground(Color.BLACK);
         setResizable(false);
        
        lvl1.setVisible(false);
        lvl2.setVisible(false);
        lvl3.setVisible(false);
        MapBackBone.setVisible(false);

        // Estimate GIF duration (ms) -- adjust to match your animation length
         Timer timer = new Timer(3000, e -> {
            MapAnim.setVisible(false);
            MapBackBone.setVisible(true);
            lvl1.setVisible(true);
            lvl2.setVisible(true);
            lvl3.setVisible(true);
        });
        timer.setRepeats(false); // run only once
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        lvl1Notif = new javax.swing.JLabel();
        lvl2Notif = new javax.swing.JLabel();
        lvl3Notif = new javax.swing.JLabel();
        lvl1Animation = new javax.swing.JLabel();
        lvl2Animation = new javax.swing.JLabel();
        lvl3Animation = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JButton();
        lvl3 = new javax.swing.JButton();
        lvl2 = new javax.swing.JButton();
        lvl1 = new javax.swing.JButton();
        MapBackBone = new javax.swing.JLabel();
        MapAnim = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 675));
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 675));
        jPanel1.setLayout(null);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HKpics/ExitBtn2.png"))); // NOI18N
        jPanel1.add(Exit);
        Exit.setBounds(3, 8, 70, 60);

        lvl1Notif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HKpics/LevelNotif1.png"))); // NOI18N
        jPanel1.add(lvl1Notif);
        lvl1Notif.setBounds(210, 270, 260, 150);

        lvl2Notif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HKpics/LevelNotif2.png"))); // NOI18N
        jPanel1.add(lvl2Notif);
        lvl2Notif.setBounds(170, 40, 260, 150);

        lvl3Notif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HKpics/LevelNotif3.png"))); // NOI18N
        jPanel1.add(lvl3Notif);
        lvl3Notif.setBounds(420, 140, 260, 150);

        lvl1Animation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HKpics/Level1.png"))); // NOI18N
        jPanel1.add(lvl1Animation);
        lvl1Animation.setBounds(247, 417, 30, 60);

        lvl2Animation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HKpics/Level2.png"))); // NOI18N
        jPanel1.add(lvl2Animation);
        lvl2Animation.setBounds(181, 187, 50, 60);

        lvl3Animation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HKpics/Level3.png"))); // NOI18N
        jPanel1.add(lvl3Animation);
        lvl3Animation.setBounds(596, 76, 44, 60);

        ExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBtnMouseExited(evt);
            }
        });
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ExitBtn);
        ExitBtn.setBounds(10, 7, 60, 60);

        lvl3.setText("3");
        lvl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lvl3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lvl3MouseExited(evt);
            }
        });
        lvl3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvl3ActionPerformed(evt);
            }
        });
        jPanel1.add(lvl3);
        lvl3.setBounds(580, 80, 79, 60);

        lvl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lvl2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lvl2MouseExited(evt);
            }
        });
        lvl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvl2ActionPerformed(evt);
            }
        });
        jPanel1.add(lvl2);
        lvl2.setBounds(160, 190, 79, 60);

        lvl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lvl1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lvl1MouseExited(evt);
            }
        });
        lvl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvl1ActionPerformed(evt);
            }
        });
        jPanel1.add(lvl1);
        lvl1.setBounds(220, 420, 79, 60);

        MapBackBone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HKpics/MapBackBone.png"))); // NOI18N
        jPanel1.add(MapBackBone);
        MapBackBone.setBounds(0, 0, 1200, 675);

        MapAnim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HKpics/MapAnim.gif"))); // NOI18N
        jPanel1.add(MapAnim);
        MapAnim.setBounds(0, 0, 1200, 675);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lvl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvl1ActionPerformed
     this.dispose();
    SwingUtilities.invokeLater(() -> {
        new LoadingFrame(() -> main.startGame()).setVisible(true);
    });
    }//GEN-LAST:event_lvl1ActionPerformed

    private void lvl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvl2ActionPerformed
     this.dispose();
    SwingUtilities.invokeLater(() -> {
        new LoadingFrame(() -> main.startGame()).setVisible(true);
    });
    }//GEN-LAST:event_lvl2ActionPerformed

    private void lvl3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvl3ActionPerformed
    this.dispose();
    SwingUtilities.invokeLater(() -> {
        new LoadingFrame(() -> main.startGame()).setVisible(true);
    });
    }//GEN-LAST:event_lvl3ActionPerformed

    private void lvl1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lvl1MouseEntered
        lvl1Animation.setVisible(true);
        lvl1Notif.setVisible(true);
    }//GEN-LAST:event_lvl1MouseEntered

    private void lvl1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lvl1MouseExited
        lvl1Animation.setVisible(false);
        lvl1Notif.setVisible(false);
    }//GEN-LAST:event_lvl1MouseExited

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        this.setVisible(false);
        new StartScreen().setVisible(true);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void ExitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseEntered
        Exit.setVisible(true);
       
    }//GEN-LAST:event_ExitBtnMouseEntered

    private void ExitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseExited
        Exit.setVisible(false);
    }//GEN-LAST:event_ExitBtnMouseExited

    private void lvl3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lvl3MouseEntered
        lvl3Animation.setVisible(true);
        lvl3Notif.setVisible(true);
    }//GEN-LAST:event_lvl3MouseEntered

    private void lvl3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lvl3MouseExited
        lvl3Animation.setVisible(false);
        lvl3Notif.setVisible(false);
    }//GEN-LAST:event_lvl3MouseExited

    private void lvl2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lvl2MouseEntered
        lvl2Animation.setVisible(true);
        lvl2Notif.setVisible(true);
    }//GEN-LAST:event_lvl2MouseEntered

    private void lvl2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lvl2MouseExited
        lvl2Animation.setVisible(false);
        lvl2Notif.setVisible(false);
    }//GEN-LAST:event_lvl2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LevelMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LevelMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LevelMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LevelMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LevelMap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JLabel MapAnim;
    private javax.swing.JLabel MapBackBone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lvl1;
    private javax.swing.JLabel lvl1Animation;
    private javax.swing.JLabel lvl1Notif;
    private javax.swing.JButton lvl2;
    private javax.swing.JLabel lvl2Animation;
    private javax.swing.JLabel lvl2Notif;
    private javax.swing.JButton lvl3;
    private javax.swing.JLabel lvl3Animation;
    private javax.swing.JLabel lvl3Notif;
    // End of variables declaration//GEN-END:variables
}
