    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hellskitchen;

import java.awt.AlphaComposite;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.Icon;
import javax.swing.JLabel;


/**
 *
 * @author Students
 */
public class StartScreen extends javax.swing.JFrame {
    
   


    
    public StartScreen() {
        setUndecorated(true);
        initComponents();
        
       
    
        register.setOpaque(false);
        register.setContentAreaFilled(false);
        register.setBorderPainted(false);
        StartBtn.setOpaque(false);
        StartBtn.setContentAreaFilled(false);
        StartBtn.setBorderPainted(false);
        exitbutton.setOpaque(false);
        exitbutton.setContentAreaFilled(false);
        exitbutton.setBorderPainted(false);
        loginIMG.setVisible(false);
        regIMG.setVisible(false);
        exitIMG.setVisible(false);
        HKtitle.setVisible(false);
  
        Icon bgIcon = BackgroundAnim.getIcon();  
        TransparentLabel newLabel = new TransparentLabel(bgIcon);
        newLabel.setAlpha(0.1f);
        newLabel.setBounds(BackgroundAnim.getBounds()); 

        jPanel1.remove(BackgroundAnim);  
        BackgroundAnim = newLabel;       
        jPanel1.add(BackgroundAnim);     
        jPanel1.setComponentZOrder(BackgroundAnim, 0);
       
      
  

    }
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ground = new javax.swing.JLabel();
        HKtitle = new javax.swing.JLabel();
        loginIMG = new javax.swing.JLabel();
        StartBtn = new javax.swing.JButton();
        regIMG = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        exitIMG = new javax.swing.JLabel();
        exitbutton = new javax.swing.JButton();
        BackgroundAnim = new javax.swing.JLabel();
        backgroundframe1 = new javax.swing.JLabel();
        Titlebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(79, 164, 252));
        jPanel1.setLayout(null);

        ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HKpics/6.png"))); // NOI18N
        jPanel1.add(ground);
        ground.setBounds(0, 520, 1200, 230);

        HKtitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HKpics/HK Title.png"))); // NOI18N
        jPanel1.add(HKtitle);
        HKtitle.setBounds(430, 110, 330, 100);

        loginIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HKpics/HK StartBTN.png"))); // NOI18N
        jPanel1.add(loginIMG);
        loginIMG.setBounds(495, 268, 190, 60);

        StartBtn.setBackground(new java.awt.Color(0, 153, 51));
        StartBtn.setFont(new java.awt.Font("Viner Hand ITC", 0, 100)); // NOI18N
        StartBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exited(evt);
            }
        });
        StartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartBtnActionPerformed(evt);
            }
        });
        jPanel1.add(StartBtn);
        StartBtn.setBounds(500, 270, 170, 50);

        regIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HKpics/HK newgamebtn.png"))); // NOI18N
        regIMG.setAlignmentY(1.0F);
        jPanel1.add(regIMG);
        regIMG.setBounds(496, 350, 190, 60);

        register.setBackground(new java.awt.Color(102, 153, 255));
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entered2(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exited2(evt);
            }
        });
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel1.add(register);
        register.setBounds(500, 360, 180, 40);

        exitIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HKpics/HK ExitBtn.png"))); // NOI18N
        jPanel1.add(exitIMG);
        exitIMG.setBounds(542, 436, 100, 40);

        exitbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entered3(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exited3(evt);
            }
        });
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(exitbutton);
        exitbutton.setBounds(540, 440, 90, 30);

        BackgroundAnim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HKpics/BGanimation.gif"))); // NOI18N
        BackgroundAnim.setMaximumSize(new java.awt.Dimension(1420, 810));
        BackgroundAnim.setMinimumSize(new java.awt.Dimension(1420, 810));
        jPanel1.add(BackgroundAnim);
        BackgroundAnim.setBounds(0, 0, 1200, 680);

        backgroundframe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HKpics/1.png"))); // NOI18N
        backgroundframe1.setMaximumSize(new java.awt.Dimension(1420, 810));
        backgroundframe1.setMinimumSize(new java.awt.Dimension(1420, 810));
        jPanel1.add(backgroundframe1);
        backgroundframe1.setBounds(0, -3, 1200, 680);

        Titlebtn.setBackground(new java.awt.Color(0, 153, 51));
        Titlebtn.setFont(new java.awt.Font("Viner Hand ITC", 0, 100)); // NOI18N
        Titlebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Titlebtnentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Titlebtnexited(evt);
            }
        });
        Titlebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitlebtnActionPerformed(evt);
            }
        });
        jPanel1.add(Titlebtn);
        Titlebtn.setBounds(430, 110, 330, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartBtnActionPerformed
       Runnable openLevelMap = () -> {
        new LevelMap().setVisible(true);
    };

    new LoadingFrame(openLevelMap).setVisible(true);
  
    this.setVisible(false);
    }//GEN-LAST:event_StartBtnActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
       AdminPasswordDialog adminDialog = new AdminPasswordDialog(this);
    adminDialog.setVisible(true);

    if (adminDialog.isAuthenticated()) {

        Runnable openLevelMap = () -> {
            new LevelMap().setVisible(true);
        };
        
        new LoadingFrame(openLevelMap).setVisible(true);
        this.setVisible(false);
    }
    }//GEN-LAST:event_registerActionPerformed

    private void entered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entered
        loginIMG.setVisible(true);
    }//GEN-LAST:event_entered

    private void exited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exited
        loginIMG.setVisible(false);
    }//GEN-LAST:event_exited

    private void entered2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entered2
        regIMG.setVisible(true);
    }//GEN-LAST:event_entered2

    private void exited2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exited2
        regIMG.setVisible(false);
    }//GEN-LAST:event_exited2

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        AdminPasswordDialog adminDialog = new AdminPasswordDialog(this);
    adminDialog.setVisible(true);
    if (adminDialog.isAuthenticated()){
        System.exit(0);
        }
    }//GEN-LAST:event_exitbuttonActionPerformed

    private void entered3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entered3
        exitIMG.setVisible(true);
    }//GEN-LAST:event_entered3

    private void exited3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exited3
        exitIMG.setVisible(false);
    }//GEN-LAST:event_exited3

    private void Titlebtnentered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Titlebtnentered
        HKtitle.setVisible(true);
    }//GEN-LAST:event_Titlebtnentered

    private void Titlebtnexited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Titlebtnexited
        HKtitle.setVisible(false);
        
    }//GEN-LAST:event_Titlebtnexited

    private void TitlebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitlebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitlebtnActionPerformed
                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        @Override
        public void run() {
            // Launch the start screen first.
            new StartScreen().setVisible(true); // Replace "StartScreen" with the name of your start screen class.
        }
    });
}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundAnim;
    private javax.swing.JLabel HKtitle;
    private javax.swing.JButton StartBtn;
    private javax.swing.JButton Titlebtn;
    private javax.swing.JLabel backgroundframe1;
    private javax.swing.JLabel exitIMG;
    private javax.swing.JButton exitbutton;
    private javax.swing.JLabel ground;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginIMG;
    private javax.swing.JLabel regIMG;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
}
