/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hellskitchen;

import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author Students
 */
public class LoadingFrame extends javax.swing.JFrame {
    
    private ImageIcon gifIn;
    private ImageIcon gifOut;


        public LoadingFrame() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        jPanel1.setBackground(Color.BLACK);

       
        gifIn = new ImageIcon("C:\\Users\\Giuz\\OneDrive - National University\\Documents\\NetBeansProjects\\HellsKitchen\\HK pics\\Load in.gif");
        gifOut = new ImageIcon("C:\\Users\\Giuz\\OneDrive - National University\\Documents\\NetBeansProjects\\HellsKitchen\\HK pics\\Load out.gif");

        
        LoadIN.setIcon(gifIn);
        LoadOUT.setIcon(gifOut);

        
        playTwoGifs();
    }

    private void playTwoGifs() {
        LoadIN.setVisible(true);
    LoadOUT.setVisible(false);

    Timer switchTimer = new Timer(5000, e -> {
        LoadIN.setVisible(false);
        LoadOUT.setVisible(true);

        Timer openMapTimer = new Timer(5700, ev -> {
            dispose();
            new LevelMap().setVisible(true);
        });
        openMapTimer.setRepeats(false);
        openMapTimer.start();

        ((Timer) e.getSource()).stop();
    });

    switchTimer.setRepeats(false);
    switchTimer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LoadIN = new javax.swing.JLabel();
        LoadOUT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);

        LoadIN.setIcon(new javax.swing.ImageIcon("C:\\Users\\Giuz\\OneDrive - National University\\Documents\\NetBeansProjects\\HellsKitchen\\HK pics\\Load in.gif")); // NOI18N
        jPanel1.add(LoadIN);
        LoadIN.setBounds(0, -8, 1200, 690);

        LoadOUT.setIcon(new javax.swing.ImageIcon("C:\\Users\\Giuz\\OneDrive - National University\\Documents\\NetBeansProjects\\HellsKitchen\\HK pics\\Load out.gif")); // NOI18N
        jPanel1.add(LoadOUT);
        LoadOUT.setBounds(0, -8, 1200, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    public static void main(String args[]) {
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoadingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoadIN;
    private javax.swing.JLabel LoadOUT;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
